image: node:10.3.0

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - echo $NPM_PRIVATE_TOKEN | base64 -d > ~/.npmrc
            - ./build/make_build.sh
